-- 코드를 입력하세요
SELECT I1.FOOD_TYPE, I1.REST_ID, I1.REST_NAME, I1.FAVORITES
FROM REST_INFO I1
WHERE FAVORITES = 
    (SELECT MAX(FAVORITES) 
     FROM REST_INFO I2
     WHERE FOOD_TYPE = I1.FOOD_TYPE)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC