-- 코드를 입력하세요
SELECT
    P.ID,
    P.NAME,
    P.HOST_ID
FROM PLACES P
JOIN (
    SELECT HOST_ID, COUNT(HOST_ID) AS CNT
    FROM PLACES
    GROUP BY HOST_ID
    HAVING CNT >= 2
) T
    ON P.HOST_ID = T.HOST_ID
ORDER BY P.ID